#!/bin/sh

# allow requiring each util from the root of the project
mv lib/*.js .
rmdir lib

# fix require paths
sed "s/\/lib//" index.js > index_.js
mv index_.js index.js
sed -i.bak "s/require('..\//require('.\//" *.js
rm *.bak
